# Generated by Django 4.2.20 on 2025-04-22 09:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='pattern_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pattern_file'),
        ),
    ]
