# Generated by Django 4.2.20 on 2025-04-22 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0002_pattern_pattern_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pattern',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
    ]
