# Generated by Django 4.2.20 on 2025-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0002_remove_crochetitem_image_remove_crochetitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crochetitem',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
