# Generated by Django 4.2.20 on 2025-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0003_crochetitem_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='crochetitem',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
