# Generated by Django 4.2.20 on 2025-04-11 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='crochetitem',
            options={'ordering': ['-created_on']},
        ),
    ]
