# Generated by Django 4.2.20 on 2025-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0006_alter_comment_options_alter_crochetitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skill_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50)),
                ('materials_needed', models.TextField()),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('category', models.CharField(choices=[('Blankets', 'Blankets'), ('Cardigans', 'Cardigans'), ('Amigurumi', 'Amigurumi'), ('Scarves', 'Scarves'), ('Hats', 'Hats'), ('Dishcloths', 'Dishcloths')], max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='projects/images/')),
                ('pattern', models.FileField(blank=True, null=True, upload_to='projects/patterns/')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.RemoveField(
            model_name='crochetitem',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CrochetItem',
        ),
    ]
