# Generated by Django 4.2.20 on 2025-04-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0008_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
