# Generated by Django 4.2.20 on 2025-04-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crochet_app', '0012_myphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPhoto',
        ),
    ]
